from setuptools import setup, find_packages

setup(
    name="opendesk",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "langchain",
        "langchain-community",
        "langchain-google-genai",
        "langchain-openai",
        "langchain-groq",
        "langchain-ollama",
        "python-dotenv",
        "requests",
        "loguru",
        "qrcode",
        "pycloudflared",
        "pydantic",
        "python-telegram-bot",
        "psutil",
        "moondream",
        "httpx",
        "pyautogui",
        "pillow",
        "python-docx",
        "pandas",
        "PyPDF2",
        "openpyxl",
        "python-pptx",
        "tictactoe-py",
        "python-chess",
        "opencv-python",
        "pyfiglet",
        "rich",
        "typer",
        "watchdog",
        "playwright",
        "beautifulsoup4",
        "googlesearch-python",
        "pyperclip",
        # Windows-only packages
        "pycaw; sys_platform == 'win32'",
        "comtypes; sys_platform == 'win32'",
        "pywin32; sys_platform == 'win32'",
        "pygetwindow; sys_platform == 'win32'",
        "pynput; sys_platform == 'win32'",
    ],
    entry_points={
        "console_scripts": [
            "opendesk=opendesk.cli:main",
        ],
    },
    python_requires=">=3.10",
)
